Update password.mdx
will fix 
pydantic_core._pydantic_core.ValidationError: 1 validation error for AppUser
username
  Field required [type=missing, input_value=ArgsKwargs((), {'identifi...vider': 'credentials'}}), input_type=ArgsKwargs]
    For further information visit https://errors.pydantic.dev/2.4/v/missing