Update password.mdx (#90)
* Update password.mdx

Current example will generate and error on load 

   def auth_callback(username: str, password: str) -> Optional[cl.User]:
                                                                ^^^^^^^
  File "/home/maximog/miniconda3/lib/python3.11/site-packages/chainlit/utils.py", line 64, in __getattr__
    module_path = registry[name]
                  ~~~~~~~~^^^^^^
KeyError: 'User'

* Update password.mdx

will fix 
pydantic_core._pydantic_core.ValidationError: 1 validation error for AppUser
username
  Field required [type=missing, input_value=ArgsKwargs((), {'identifi...vider': 'credentials'}}), input_type=ArgsKwargs]
    For further information visit https://errors.pydantic.dev/2.4/v/missing